---

- name: Write tor configuration
  template:
    src: 'torrc.j2'
    dest: '/etc/tor/torrc'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify:
  - restart tor

- meta: flush_handlers

- name: Ensure tor is running
  service:
    name: 'tor'
    state: 'running'
