---

## install
- include: install_tor_apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: install_tor_yum.yml
  when: ansible_pkg_mgr == 'yum'

- include: configure_obfs4proxy.yml
  when: (ansible_pkg_mgr == 'apt' and tor_obfs4proxy_enabled)

- include: install_pip_obfsproxy.yml
  when: tor_obfsproxy_home is defined


## configure

- include: hidden_services.yml
  when: tor_hidden_services is defined

- include: configure_apt_single.yml
  when: proc_instances is not defined

- include: configure_tor_instance.yml
  when: proc_instances is defined

## wait for hidden services
- include: wait_for_hidden_services.yml
  when: tor_wait_for_hidden_services
